---

- name: Verify if virtualization is enabeld
  ansible.builtin.import_tasks:
    name: verify

- name: Install needed packages for Ubuntu to be a hypervisor
  ansible.builtin.apt:
    pkg: "{{ kvm_packages }}"

# - name: Register all files in /etc/netplan/
#   ansible.builtin.find:
#     paths: /etc/netplan
#   register: netplan_files

# - name: Remove all files in /etc/netplan/
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     state: absent
#   loop: netplan_files.files


# - name: Update netplan file
#   ansible.builtin.template:
#     src: templates/netplan_static-ip_bridge.yaml.j2
#     dest: /etc/netplan/static-bridge.yaml
#     owner: root
#     group: root
#     mode: '0644'

# https://github.com/dmacvicar/terraform-provider-libvirt/commit/22f096d9
- name: Disable SELinux enforcement in qemu.conf
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^security_driver = "none"$'
    insertafter: '^#security_driver = "selinux"$'
    line: security_driver = "none"

- name: Enable libvirtd to start on boot
  ansible.builtin.systemd:
    name: libvirtd.service
    state: started
    enabled: true

- name: Restart libvirtd to ensure it does not self influct selinux
  ansible.builtin.systemd:
    name: libvirtd.service
    state: restarted

# - name: Copy systemd config to host
#   ansible.builtin.template:
#     src: templates/start-vm-domains.service
#     dest: /etc/systemd/system/start-vm-domains.service
#     owner: root
#     group: root
#     mode: '0644'
#   tags: systemd

# - name: Copy VM startup script for systemd
#   ansible.builtin.template:
#     src: templates/start-vms-that-are-shut-off.sh
#     dest: /usr/local/bin/start-vms-that-are-shut-off.sh
#     owner: root
#     group: root
#     mode: '0755'
#   tags: systemd

# - name: Reload systemd configurations
#   ansible.builtin.systemd:
#     daemon_reload: true
#   tags: systemd

# - name: Enable start-vm-domains.service
#   ansible.builtin.systemd:
#     name: start-vm-domains.service
#     enabled: true
#   tags: systemd

# - name: Enable start-vm-domains.service
#   ansible.builtin.systemd:
#     name: start-vm-domains.service
#     state: started
#     no_block: true
#   tags: systemd
